name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@8135e21710aebfd84778a4291298eb1c6568e20b # main
    permissions:
      contents: read
      actions: read
