name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@f3332ff4124e0e2eb8acb10d8cd930694814c216 # main
    permissions:
      contents: read
      actions: read
