name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@ff21f94ddad852793d4ef2088103a11ffc386477 # main
    permissions:
      contents: read
      actions: read
