name: GitHub Actions Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@8c50ed3d1d5b4b7a113385add28e75cd229add0d # main
    permissions:
      contents: read
